Add 2 endpoints to manage the challenges and their statuses
InsecurityAsso/inshack-scoreboard pull request #5
Opened 2019-03-26 21:37 UTC by HugoDelval

@koromodako with this you'll be able to update mkctf to add those features:
- generate a json which describes the challenges (flag, description...), which we can push to the scoreboard to update the challenges quicker than before
- add the job that exploit all the challenges and generate a json which we can push to the scoreboard to let it know which challs are up/down

2019-03-26 22:00 UTC, 3wnbr1 approved these changes

2019-03-27 06:38 UTC, koromodako requested changes
Voir commentaires dans le fichier `app/challenges/views.py`

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +              "chall_file": null OR "url of the static files for the chal",
`static_url` au lieu de `chall_file` ?

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +              "category": Any of: "MIC", "WEB", "PPC", "FOR", "REV", "PWN", "CRY", "NET",
`tags` ou `categories` de type `string[]` au lieu de `category` ?
On ne classe plus les challenges par catégorie sachant que la majorité d'entre eux couvrent plusieurs catégories :)

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +              "description": "Fun story in html",
Aujourd'hui la description stockée au niveau système de fichiers est en markdown, est-ce que cela signifie que je dois la convertir (avec `pandoc` par exemple) avant de te la pousser ? Django n'a rien d'intégré pour la conversion ?

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +              "difficulty": 0-4 (0 easier, 4 harder),
Je ne crois pas qu'on stocke cette information aujourd'hui et ça me semble risqué d'évaluer la difficulté d'un challenge en tant que créateur de ce challenge. C'est un peu philosophique comme remarque mais c'est une vraie question. Est-on vraiment capable de mesurer la difficulté d'un challenge ? Ça me semble très relatif perso.

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +        challenges = json.loads(request.body)
Il me semble qu'il est déconseillé de manière générale d'échanger des listes directement au format JSON. Il me semble que dans ce cas-là il faudrait que j'envoie un body qui contient :
`{"challenges":[...]}`

2019-03-27 06:38 UTC, koromodako commented on app/challenges/views.py
> +@staff_member_required_basicauth
Si je comprends bien,on devra créer un compte staff spécifique pour le script qui pousse à intervalles réguliers le statut des challenges. C'est bien ça ?

2019-04-10 06:08 UTC, HugoDelval commented on app/challenges/views.py
> +              "chall_file": null OR "url of the static files for the chal",
Je changerai ça ! https://github.com/InsecurityAsso/inshack-scoreboard/issues/7

2019-04-10 06:09 UTC, HugoDelval commented on app/challenges/views.py
> +              "category": Any of: "MIC", "WEB", "PPC", "FOR", "REV", "PWN", "CRY", "NET",
Alors on peut faire ça mais ça demande un peu de dev

2019-04-10 06:12 UTC, HugoDelval commented on app/challenges/views.py
> +              "difficulty": 0-4 (0 easier, 4 harder),
Tu ne crois pas qu'on stocke cette info où ? Historiquement sur le scoreboard les challenges sont triées par points (dynamiques) puis par difficulté estimée par le créateur, ça permet tout de même de donner une idée aux gens quand le CTF commence, je pense que c'est une bonne idée de le garder

2019-04-10 06:13 UTC, HugoDelval commented on app/challenges/views.py
> +@staff_member_required_basicauth
Ce sera le même compte (user:mdp) que le compte qui permet d'accéder à l'interface admin du scoreboard

2019-04-10 06:14 UTC, HugoDelval commented on app/challenges/views.py
> +        challenges = json.loads(request.body)
Je fais ça :+1: https://github.com/InsecurityAsso/inshack-scoreboard/issues/8

2019-04-10 15:05 UTC, koromodako commented on app/challenges/views.py
> +              "difficulty": 0-4 (0 easier, 4 harder),
Ok pas de problème, ce n'est pas une info indiquée dans mkctf. La difficulté d'un challenge est souvent remise en question par les joueurs.

2019-04-10 15:07 UTC, koromodako commented on app/challenges/views.py
> +              "category": Any of: "MIC", "WEB", "PPC", "FOR", "REV", "PWN", "CRY", "NET",
Pas urgent au pire on demande aux créateurs de garder la catégorie principale mais encore une fois donner une seule catégorie reflète rarement la réalité.

2019-04-10 19:32 UTC, HugoDelval commented on app/challenges/views.py
> +        challenges = json.loads(request.body)
En vrai je trouve ça con comme restriction :p t'as vu ça où par curiosité ?

2019-04-10 19:43 UTC, merged